import argparse
import json
from pathlib import Path
from datetime import datetime

import ollama


BASE_DIR = Path(__file__).resolve().parent
PROMPT_PATH = BASE_DIR / "prompts" / "virtual_hacker_prompt.txt"
TARGET_PATH = BASE_DIR / "examples" / "target_chatbot.json"
OUTPUT_DIR = BASE_DIR / "outputs"


def load_text_file(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    return path.read_text(encoding="utf-8")


def load_json_file(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def build_user_message(target_system: dict) -> str:
    target_json = json.dumps(target_system, indent=2, ensure_ascii=False)

    return (
        "Analyze the following LLM-based chatbot system.\n\n"
        "Target system description:\n\n"
        f"{target_json}\n\n"
        "Generate the defensive risk report following the required markdown format."
    )


def generate_risk_report(system_prompt: str, user_message: str, model_name: str) -> str:
    response = ollama.chat(
        model=model_name,
        messages=[
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ],
    )

    return response["message"]["content"]


def safe_filename(model_name: str) -> str:
    return model_name.replace(":", "_").replace("/", "_").replace("\\", "_")


def save_report(report: str, model_name: str) -> Path:
    OUTPUT_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    model_file_name = safe_filename(model_name)

    output_path = OUTPUT_DIR / f"risk_report_{model_file_name}2.md"

    final_report = f"""<!--
Generated by Virtual Hacker
Model: {model_name}
Timestamp: {timestamp}
-->

{report}
"""

    output_path.write_text(final_report, encoding="utf-8")
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Virtual Hacker - Defensive risk analysis for LLM-based chatbots"
    )

    parser.add_argument(
        "--model",
        type=str,
        default="qwen2.5:7b",
        help="Ollama model name to use, for example qwen2.5:7b or mistral:7b",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()
    model_name = args.model

    print(f"Using model: {model_name}")

    print("[1/4] Loading Virtual Hacker prompt...")
    system_prompt = load_text_file(PROMPT_PATH)

    print("[2/4] Loading target chatbot description...")
    target_system = load_json_file(TARGET_PATH)

    print("[3/4] Generating risk report with Ollama...")
    user_message = build_user_message(target_system)
    report = generate_risk_report(system_prompt, user_message, model_name)

    print("[4/4] Saving report...")
    output_path = save_report(report, model_name)

    print(f"Done. Report saved in: {output_path}")


if __name__ == "__main__":
    main()